print("000560_04_01_Exception.py")

num1 = 7
num2 = 0
print(num1/num2)